import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import SectionContainer from '@/components/SectionContainer';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { cn } from '@/lib/utils';

import { ThemeProvider } from 'next-themes';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="light"
      enableSystem
      disableTransitionOnChange
    >
      <div className="flex min-h-screen w-full flex-col justify-between">
        <div>
          <Header />
          <SectionContainer>
            <main
              className={cn('min-h-screen bg-background font-sans antialiased')}
            >
              {children}
            </main>
          </SectionContainer>
        </div>
        <Footer />
      </div>
    </ThemeProvider>
  );
}
